# parameters values will be passed from the main/parent yaml template.
parameters:
  environment: dev
  environmentDisplayName: Development
  backendServiceArm: ''
  backendAzureRmResourceGroupName: 'rg-terraform-state'
  backendAzureRmStorageAccountName: 'tfstate20250923db'
  backendAzureRmContainerName: 'tfstate'
  backendAzureRmKey: 'dev.tfstate'
  workingDirectory: 'terraform'
  location: 'westeurope'
  anyTfChanges: false
  dependsOn: []

stages:

- stage: ${{ parameters.environment }}
  displayName: Deploy to ${{ parameters.environmentDisplayName }}
  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: Terraform_Plan
    displayName: Terraform Init, Plan & Apply
    pool:
      vmImage: ubuntu-latest

    steps:
    
    - task: Bash@3
      displayName: Install Terraform v1.5.7
      inputs:
        targetType: 'inline'
        script: |
          # Check if Terraform is already installed with correct version
          if command -v terraform &> /dev/null; then
            CURRENT_VERSION=$(terraform version -json | jq -r '.terraform_version' 2>/dev/null || echo "unknown")
            if [ "$CURRENT_VERSION" = "1.5.7" ]; then
              echo "Terraform v1.5.7 is already installed"
              terraform version
              exit 0
            fi
          fi
          
          echo "Installing Terraform v1.5.7..."
          
          # Download Terraform
          TERRAFORM_VERSION="1.5.7"
          DOWNLOAD_URL="https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
          
          echo "Downloading from: $DOWNLOAD_URL"
          
          # Clean up any existing files/directories that might conflict
          rm -f terraform.zip
          # Handle both file and directory cases for 'terraform'
          if [ -f terraform ]; then
            rm -f terraform
          elif [ -d terraform ]; then
            echo "Found terraform directory, working around it..."
          fi
          
          # Download and extract to a temporary name first
          curl -fsSL "$DOWNLOAD_URL" -o terraform.zip
          unzip -o terraform.zip terraform -d /tmp/
          
          # Make executable and move to PATH
          chmod +x /tmp/terraform
          sudo mv /tmp/terraform /usr/local/bin/terraform
          
          # Clean up
          rm -f terraform.zip
          
          # Verify installation
          echo "Terraform installation completed:"
          terraform version
    
    - task: AzureCLI@2
      displayName: terraform init with Azure backend
      inputs:
        azureSubscription: ${{ parameters.backendServiceArm }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: ${{ parameters.workingDirectory }}
        addSpnToEnvironment: true
        inlineScript: |
          # Set and verify Terraform environment variables for service principal authentication
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          
          # Disable Azure CLI authentication methods
          export ARM_USE_CLI=false
          export ARM_USE_MSI=false
          export ARM_USE_OIDC=false
          
          # Debug: Display authentication info (without secrets)
          echo "=== Authentication Configuration ==="
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_USE_CLI: $ARM_USE_CLI"
          echo "ARM_CLIENT_SECRET: [REDACTED - Length: ${#ARM_CLIENT_SECRET}]"
          echo "===================================="
          
          # Verify required variables are set
          if [[ -z "$ARM_CLIENT_ID" || -z "$ARM_CLIENT_SECRET" || -z "$ARM_TENANT_ID" || -z "$ARM_SUBSCRIPTION_ID" ]]; then
            echo "ERROR: Missing required ARM authentication variables"
            exit 1
          fi
          
          terraform init \
            -backend-config="resource_group_name=${{ parameters.backendAzureRmResourceGroupName }}" \
            -backend-config="storage_account_name=${{ parameters.backendAzureRmStorageAccountName }}" \
            -backend-config="container_name=${{ parameters.backendAzureRmContainerName }}" \
            -backend-config="key=${{ parameters.backendAzureRmKey }}"
    
    - task: AzureCLI@2
      displayName: terraform validate
      inputs:
        azureSubscription: ${{ parameters.backendServiceArm }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: ${{ parameters.workingDirectory }}
        addSpnToEnvironment: true
        inlineScript: |
          # Set Terraform environment variables for service principal authentication
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_USE_CLI=false
          export ARM_USE_MSI=false
          export ARM_USE_OIDC=false
          
          terraform validate
    
    - task: AzureCLI@2
      displayName: terraform plan -var environment=${{ parameters.environment }} -out=${{ parameters.backendAzureRmKey }}
      inputs:
        azureSubscription: ${{ parameters.backendServiceArm }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: ${{ parameters.workingDirectory }}
        addSpnToEnvironment: true
        inlineScript: |
          # Set Terraform environment variables for service principal authentication
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_USE_CLI=false
          export ARM_USE_MSI=false
          export ARM_USE_OIDC=false
          
          terraform plan -var environment=${{ parameters.environment }} -var location=${{ parameters.location }} -out=${{ parameters.backendAzureRmKey }}
    
    - task: PowerShell@2
      displayName: detect any terraform change in the plan
      inputs:
        workingDirectory: ${{ parameters.workingDirectory }}
        targetType: 'inline'
        script: |
          try {
            $plan = $(terraform show -json ${{ parameters.backendAzureRmKey }} | ConvertFrom-Json)
            $actions = $plan.resource_changes.change.actions
            Write-Host "Terraform actions : $actions"
            if (($actions -contains 'create') -or ($actions -contains 'delete') -or ($actions -contains 'update'))
            {
              Write-Host "Terraform will perform the following actions : $actions"
              Write-Host "##vso[task.setvariable variable=anyTfChanges;]true"
            }
            else
            {
              Write-Host "There is no change detected in Terraform tfplan file"
              Write-Host "##vso[task.setvariable variable=anyTfChanges;]false"
            }
          }
          catch {
            Write-Error "Error analyzing Terraform plan: $_"
            Write-Host "##vso[task.setvariable variable=anyTfChanges;]false"
            exit 1
          }
    
    - task: AzureCLI@2
      displayName: terraform apply ${{ parameters.backendAzureRmKey }}
      condition: eq(variables.anyTfChanges, true)
      inputs:
        azureSubscription: ${{ parameters.backendServiceArm }}
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        workingDirectory: ${{ parameters.workingDirectory }}
        addSpnToEnvironment: true
        inlineScript: |
          # Set Terraform environment variables for service principal authentication
          export ARM_CLIENT_ID=$servicePrincipalId
          export ARM_CLIENT_SECRET=$servicePrincipalKey
          export ARM_TENANT_ID=$tenantId
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          export ARM_USE_CLI=false
          export ARM_USE_MSI=false
          export ARM_USE_OIDC=false
          
          terraform apply -auto-approve ${{ parameters.backendAzureRmKey }}
